

org:
  jobrunr:
    database:
      skip-create: false
    jobs:
      default-number-of-retries: 0
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
      worker-count: 4
      poll-interval-in-seconds: 5
      metrics:
        enabled: true
    dashboard:
      enabled: true
      port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlops
    username: root
    password: Hoangdao192@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl